export const createRestaurantBody = {
  name: 'Sample Restaurant',
  description: 'Open Monday-Friday 9am-10pm, Saturday-Sunday 10am-11pm',
  phone: '+1 (555) 123-4567',
  email: 'contact@samplerestaurant.com',
  website: 'https://www.samplerestaurant.com',
  imageUrl: 'https://logopond.com/logos/a447d60b6c1ffcfcb618ed05ecd9a679.png',
  cuisine: 'Italian',
  priceRange: '$$$',
  capacity: 120,
  isActive: true,
  location: {
    street: '123 Main Street',
    city: 'New York',
    state: 'NY',
    zipCode: '10001',
    country: 'United States',
    formattedAddress: '123 Main Street, New York, NY 10001, United States',
    latitude: 40.7128,
    longitude: -74.006,
    locationType: 'ROOFTOP',
    plusCode: '87G8Q9XX+XX',
    businessStatus: 'OPERATIONAL',
    utcOffset: -240,
    timezone: 'America/New_York',
    isVerified: true,
    toString: '123 Main Street, New York, NY 10001',
  },
};
